name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod  # Make sure your angular.json outputPath is set to 'dist/your-project-name'

      - name: Deploy to Firebase Hosting
        uses: wzieba/Firebase-Action@v2
        with:
          firebase_credentials: 1//03mxb6-BuNcffCgYIARAAGAMSNwF-L9IrN2e6RaI8eKPNvTkY9LP_spv18hlccWfcv0gT3b_4uuqKFt8RuLPo4M1WWYWV1PDbfVU  # Firebase service account key
          project_id: ataplus-25f58  # Replace with your Firebase project ID